### ISSUE TITLE
Problem with allocPTPage() in SVA/lib/mmu.c

### ISSUE THREAD

**Issue by XiaowanDong** [jtcriswell/SVA#10]
1. Here https://github.com/XiaowanDong/SVA/blob/master/SVA/lib/mmu.c#L1006, p is a pointer, so it should be compared against NULL instead of 0.
2.  This line https://github.com/XiaowanDong/SVA/blob/master/SVA/lib/mmu.c#L1030 should be moved into the if statement above it.

**Comment by jtcriswell** [comment]
Correct and correct.  Please make the necessary changes, test them, and commit.

**Comment by XiaowanDong** [comment]
Thanks Alan for pointing them out.

**Comment by jtcriswell** [comment]
Fixed in Revision 40c6e6a0cfc0b13998fd6b081258a39ebc642bea.
