### ISSUE TITLE
Incorrect bound checking in secmem.c

### ISSUE THREAD

**Issue by whonore** [jtcriswell/SVA#2]
The function `freeSecureMemory()` in secmem.c tries to check if a value is within a range by chaining the comparisons together (`SECMEMSTART <= pint < SECMEMEND`).

**Comment by jtcriswell** [comment]
whonore fixed this.   Commit 52fed510dfd6da7aa5253b38d4f38727c62cd6af pulls the fix into the SVA source tree.
