### ISSUE TITLE
randomNumber should properly loop after RDRAND call if CF Flag is unset

### ISSUE THREAD

**Issue by irichter** [jtcriswell/SVA#22]
Per the [Intel Software Developer's Manual](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf), RDRAND will set the CF flag to indicate success or failure (e.g.: in case of insufficient entropy) of the instruction.

The inline assembly in randomNumber() does check this flag (via JAE), but the resulting jump is to location 0x1, rather than label "1". Perhaps [this](https://stackoverflow.com/a/3898451) could inspire a relevant fix.

Also, note [sample code that uses a fixed number of retries](https://en.wikipedia.org/wiki/RdRand#Sample_x86_asm_code_to_check_upon_RDRAND_instruction).

**Comment by jtcriswell** [comment]
Fixed in commit 43f9c2e6d2c5a2418f5b31d0ebe908ca8c086fc5.
