### ISSUE TITLE
Is this the KCoFI version of SVA or the memory safety version?

### ISSUE THREAD

**Issue by ndauten** [jtcriswell/SVA#5]
Hi @jtcriswell is this the KCoFI source?

If so we should mention that in the read me.

**Comment by jtcriswell** [comment]
This is the source code for Virtual Ghost, KCoFI, and (more generally) the source code to SVA (which underlies all of these systems).  I agree that we should mention it in the README.

I have fixed this in commit 3113a882e21e7da6d1fdcdb8d2df4bb4607b8bde.  Please take a look and let me know what you think.

**Comment by ndauten** [comment]
This looks great! Thanks for updating it.
